# Generated by Django 4.0.5 on 2022-07-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_company_child_company_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name='child', to='accounts.company'),
        ),
    ]
