# Generated by Django 4.0.5 on 2022-06-28 09:15

from django.db import migrations, models
import realEstate.apps.products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.CharField(default=realEstate.apps.products.models.nanoid_generate, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default='123', max_length=25)),
            ],
        ),
    ]
